spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: anywhere
  datasource:
    url: jdbc:mysql://localhost:3306/anywheredb
    username: anywhere
    password: anywhere
    driver-class-name: com.mysql.cj.jdbc.Driver